### ISSUE TITLE
[Archlinux] Chromium won't start : cannot open libre2 object file

### ISSUE THREAD

**Issue by URemery** [Eloston/ungoogled-chromium#1031]
**Describe the bug**
Ungoogled chromium won't start on archlinux because it's looking for libre2.so.6 library but arch provides libre2.so.7 by default. 
Also, the ungoogled-chromium package is flagged out of date on the AUR.

**To Reproduce**
To see the error message you have to start chromium from a terminal. 
See bellow.

`[ugor@archlinux ~]$ chromium
/usr/lib/chromium/chromium: error while loading shared libraries: libre2.so.6: cannot open shared object file: No such file or directory`

`[ugor@archlinux ~]$ ls /usr/lib | grep libre2.so
libre2.so
libre2.so.7
libre2.so.7.0.0
`

**Environment :**
 - OS/Platform and version: Up-to-date archlinux
 - ungoogled-chromium version: 81.0.4044.129-1

**Temporary solution**
I created a symbolic link called /usr/lib/libre2.so.6 pointing to /usr/lib/libre2.so, but that is really dirty.

**Expected behavior**
If possible, make ungooggled-chromium use the libre2 version provided by default by archlinux repositories.

**Comment by mbakke** [comment]
This can be fixed by rebuilding ungoogled-chromium against the newer `libre2`.

Alternatively you can use [GNU Guix](https://guix.gnu.org/) to install ungoogled-chromium, a third party package manager which works on all distributions and makes such issues impossible by design.  It also has the latest version.

**Comment by PF4Public** [comment]
> Alternatively you can use [GNU Guix](https://guix.gnu.org/) to install ungoogled-chromium, a third party package manager which works on all distributions and makes such issues impossible by design. It also has the latest version.

Repeating this from post to post makes it look like some kind of advertisement…

**Comment by mbakke** [comment]
Well, it is :-)

Guix solves a lot of problems in the package management space, such as not needing root privileges and allowing roll-backs.   It is also more up to date than most distributions, rivalled only by Arch.

Being an official GNU project, it has a strong stance on freedom and privacy, and to my knowledge the only ungoogled-chromium package that takes care to remove the proprietary UnRAR code.  ungoogled-chromium is also a "first-class" citizen in Guix, as the regular Chromium is considered spyware by GNU.

Anyway, I'll try to tone it down a bit and instead send a PR for the README to clarify that Guix can be used on any GNU/Linux distribution.

**Comment by Ph0rk0z** [comment]
Just link re2.6 to re2.7, works fine for me

**Comment by URemery** [comment]
> This can be fixed by rebuilding ungoogled-chromium against the newer `libre2`.

Thank you mbakke,  I'll do it tonight.

> Just link re2.6 to re2.7, works fine for me

Yeah it works but I'm not sure that it's a good idea to ignore version changes, I prefer to rebuild to avoid any further problems.

**Comment by URemery** [comment]
Just tried to rebuild ungoogled-chromium with re2.7. Had the following build error :
`../../components/autofill/core/browser/address_rewriter.cc:60:11: error: no member named 'set_utf8' in 're2::RE2::Options'
  options.set_utf8(true);`

I'll do with the symlink tweak until I can rebuild with re2.7.

Should I close this thread and open and new issue dedicated to this build error ?

**Comment by jstkdng** [comment]
@URemery 
You have to add a new patch: https://github.com/jstkdng/ungoogled-chromium-archlinux/blob/master/clean-up-a-call-to-set_utf8.patch
You can try building my fork, it has no problems so far.

**Comment by Eloston** [comment]
Closing as duplicate of https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/77

**Comment by PF4Public** [comment]
@mbakke 
> the only ungoogled-chromium package that takes care to remove the proprietary UnRAR code

Is there something more to do besides applying [ungoogled-chromium/patches/core/debian/disable/unrar.patch](https://github.com/Eloston/ungoogled-chromium/blob/master/patches/core/debian/disable/unrar.patch)?

**Comment by kevinlekiller** [comment]
From what I can see, the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ungoogled-chromium#n77) runs [patches.py](https://github.com/Eloston/ungoogled-chromium/blob/master/utils/patches.py) which iterates over all folders / files in the [patches](https://github.com/Eloston/ungoogled-chromium/tree/master/patches) folder, there's nothing that I see in there that excludes applying the debian patches.

**Comment by mbakke** [comment]
@PF4Public That should suffice.  You probably also want to delete third_party/unrar to ensure it does not get included elsewhere in the future.

**Comment by PF4Public** [comment]
> @PF4Public That should suffice. You probably also want to delete third_party/unrar to ensure it does not get included elsewhere in the future.

That means that any package following this repo _does_ take care of removing UnRAR code and the statement of Guix uniqueness in this regard is no more than a mere exaggeration.

Anyway, I'm trying to say, that there is no silver bullet that solves all issues for all users, and there is no need (in my very humble opinion) to reiterate a solution that worked for some. People might have no troubles with their current setup and do not ask for a solution! There might be nothing but a slight nuisance to overcome.

I'm not trying to start a comment war, just trying to convey my thought. I won't be writing more.

**Comment by mbakke** [comment]
@PF4Public Oh my, I was not aware that patch was in "core".  My apologies for the incorrect accusation and comment!  And thanks for the correction.

Guix tracks Debians patches directly, and in my caffeine-deprived state I thought you linked to the Debian repository.  Thanks, and sorry!
